### ISSUE TITLE
real time TX → Real Time TXに文言修正してほしい

### ISSUE THREAD

**Issue by fortunecrypto** [DeFiGeek-Community/yamato-interface#100]
### 要望の種類

B UIについて

### 新機能や改善の概要

〇 表記の修正
・ real time TX → Real Time TX

〇 備考
画面右上部分

〇 参考
https://discord.com/channels/705052448418693180/899916069161041931/905882422716006452

**Comment by 0xTeaTwo** [comment]
figmaの修正も必要
