### ISSUE TITLE
変動予測値表示 → 変動予測値に文言修正してほしい

### ISSUE THREAD

**Issue by fortunecrypto** [DeFiGeek-Community/yamato-interface#102]
### 要望の種類

B UIについて

### 新機能や改善の概要

〇 表記の修正
・ 変動予測値表示 → 変動予測値

〇 備考
借入量入力フォームの下

〇 参考
https://discord.com/channels/705052448418693180/899916069161041931/905882422716006452

**Comment by 0xTeaTwo** [comment]
figmaの修正も必要
