### ISSUE TITLE
 数値と単位の間に半角スペースを追加してほしい

### ISSUE THREAD

**Issue by fortunecrypto** [DeFiGeek-Community/yamato-interface#103]
### 要望の種類

B UIについて

### 新機能や改善の概要

〇 表記の修正
・ 数値と単位の間に半角スペースを追加

〇 備考
画面各所、10ヵ所程度

〇 参考
https://discord.com/channels/705052448418693180/899916069161041931/905882422716006452

**Comment by 0xTeaTwo** [comment]
figmaの修正も必要
