### ISSUE TITLE
各入力フォームの初期値 0 を撤廃してほしい

### ISSUE THREAD

**Issue by fortunecrypto** [DeFiGeek-Community/yamato-interface#104]
### 要望の種類

B UIについて

### 新機能や改善の概要

〇 表記・初期値の修正
・ 各入力フォームの初期値 0 を撤廃

〇 備考
数値を入力すると既存の0が残っているため意図しない入力、例えば1を入力したいのに10になってしまうなどの入力ミスを誘発する可能性があるため

〇 参考
https://discord.com/channels/705052448418693180/899916069161041931/905882422716006452

**Comment by 0xTeaTwo** [comment]
formikを調査して、対応する。

**Comment by taka0409** [comment]
初期値を空文字、空文字と数値を許容することで表題の件については対応できました。
空文字でのサブミットはエラーとする必要がありますが、上記のようにバリデーションを対応しているのでフォームの下の赤文字として表示ができません。
サブミット時と入力のonChangeイベント時でバリデーションを分ける機能は見つけられませんでした。
空文字のサブミットはMetamaskのエラーの時のようにerrorToastで出す、で問題ないでしょうか？
1フォームだけ対応したものならお見せできるので、検討お願いします。

**Comment by fortunecrypto** [comment]
仕様決定には0xTwoさんの意見も伺いたいですが、他のエラーチェックとは異なり実装が困難になってしまうならエラーの表示方法が異なっても問題ないと思います。

初期状態で実行ボタンをdisableにしてしまって、フォームに入力イベントが起きた時にvalidationと一緒にボタンを有効化するみたいなのはどうでしょう？

**Comment by taka0409** [comment]
> 初期状態で実行ボタンをdisableにしてしまって、フォームに入力イベントが起きた時にvalidationと一緒にボタンを有効化するみたいなのはどうでしょう？
空文字の時に実行ボタンをdisableにするのは可能です。

**Comment by fortunecrypto** [comment]
> 空文字の時に実行ボタンをdisableにするのは可能です。
この仕様にてお願いします！

**Comment by 0xTwo** [comment]
formikの設計からすると、バリデーションの中でフォームの状態を取得して、`"入力中"(dirty)かつ値が空文字`なら必須入力エラーにするということが考えられるかなと思います。

ただ、難しそうならchromeで動作確認できているボタン無効化で十分かなと思います。

`input[type="number"]`で文字列の空文字を想定値の一つに入れることは無理にやることだと思っていなくて（ブラウザの種類によってもこの辺のハンドリングはいろいろ変わりますから）、このイシューは`v1` `v2`のリリースラベルを貼っていませんでした。（できるなら、GOです👍）

**Comment by taka0409** [comment]
@0xTwo 

> formikの設計からすると、バリデーション関数の中でフォームの状態を用いて、"入力中"(dirty)かつ値が空文字なら必須入力エラーにするということが考えられるでしょうか。

- 空文字の時にエラーは出さない
- 空文字の時は実行ボタンを押せない
- input[type="number"]で入力を数値に制限する

という形で解決しています。

> input[type="number"]で文字列の空文字を想定値の一つに入れることは無理にやることだと思っていなくて（ブラウザの種類によってもこの辺のハンドリングはいろいろ変わりますから）

Chromeでの動作確認とテストの通過はしていますが、TypeScriptの型推論に頼った若干無理のある実装感は否めないので、レビューいただいて筋がよくなければrejectしていただいて構いません。
