### ISSUE TITLE
有効なボタンと無効なボタンの色が類似しているので配色を見直してほしい

### ISSUE THREAD

**Issue by fortunecrypto** [DeFiGeek-Community/yamato-interface#105]
### 要望の種類

B UIについて

### 新機能や改善の概要

〇 デザイン/表示の修正
・有効なボタンと無効なボタンの色が類似しているため区別しづらいので、有効なボタンを濃くするか色の系統を変えるなどぱっと見て違いが分かるようにして欲しい

〇 備考
デザインに関わってくるので色の変更についてはデザイン担当と相談してください

**Comment by 0xTeaTwo** [comment]
figmaが必要

**Comment by 0xTeaTwo** [comment]
72時間のロックタイム中に引出実行ボタンが押せない際の表示と同じ方法でボタンを無効にする
- 預入前の場合 → 引出実行、借入量入力、返済実行ボタン
- 償還、Yamato償還、Yamato代位弁済の各候補総量が0の場合 → 償還実行、Yamato償還実行、代位弁済実行ボタン
