### ISSUE TITLE
少数を含む返済で全額返済ができなくなってしまうケースがある

### ISSUE THREAD

**Issue by fortunecrypto** [DeFiGeek-Community/yamato-interface#109]
### 現象の種類

A 動作の問題

### 見つかった現象及び動作

ごく小さい数値の返済を行うと、返済実行時に入力した数値とは異なる返済数量が実行されてしまい、UI上から完済することが不可なくらい最小単位での返済となってしまう。
コントラクトを直呼び出しする事で完済は可能

通常の使い方ではないので優先度は低いが、入力ミスなどで一度これに嵌ってしまうと完済ができなくてすっきりしない可能性あり。

### 問題のTxn Hash

https://rinkeby.etherscan.io/tx/0x6b79efe1e798c9591d280e94a499e7451fffff1955d08254dab48acd337f5654

### 検証環境：ブラウザ種別

Chrome

### Web3 インターフェース

Metamask

### 再現性について

再現できる

### 再現手順

1. 返済に少数第8以下のごく少数な数値を入力する、（0.00000009 を返済）
2. 入力した数値とは異なる返済額になる （0.000000003486784401）
3. UIからは細かい正確な数字を返済できないため、完済が不可となる ＝預け入れETHを完全には引き出すことはできなくなる

### 詳細説明、考察、備考など

UI側で扱える少数の精度限界？
貸出は整数、返済は少数第3位までに条件を付けてしまって良いか

**Comment by 0xTeaTwo** [comment]
https://github.com/DeFiGeek-Community/yamato-interface/issues/73 による二次災害。
ethersが指数表記(e形式)に対応しないことが根本にあるし、そうする理由も納得である。wei入力をがんばるなら、eth単位の入力フォームとは別にwei単位の専用入力フォームを用意するなどが現実的である。

**Comment by 0xTeaTwo** [comment]
今回のパターンには対応しました。`0.00000009`のままで処理できます。
