### ISSUE TITLE
CJPYプライスと市場間価格差異の表示方法の改善

### ISSUE THREAD

**Issue by fortunecrypto** [DeFiGeek-Community/yamato-interface#117]
### 要望の種類

B UIについて

### 新機能や改善の概要

「CJPYプライス」と「市場間価格差異」の表示が少し分かりづらいため次のように変更する。

１．「CJPYプライス」は不要なため破棄
２．「市場間価格差異」は 各取引所毎に 現在価格と乖離率を併記する。
３． 乖離率がマイナスの場合は 乖離率の部分を赤字フォントで表示 （現場判断で棄却可）
４.　それぞれの取引所名&価格の行ごとに、該当取引所のスワップページへ遷移できるリンクがある（別タブで開く）

（表記例）
uniswap(v3): ¥0.578 （-42.2%）
uniswap(v2): ¥0.6 (-40%)

**Comment by 0xTwo** [comment]
> ３． 乖離率がマイナスの場合は 乖離率の部分を赤字フォントで表示 （現場判断で棄却可）

#133 では対応保留のため別イシューに残す
https://github.com/DeFiGeek-Community/yamato-interface/pull/133#issuecomment-1035964298
