### ISSUE TITLE
Yamato Tool TCRが個人の担保率になってる

### ISSUE THREAD

**Issue by ghost** [DeFiGeek-Community/yamato-interface#131]
### 現象の種類

A 動作の問題

### 見つかった現象及び動作

![image](https://user-images.githubusercontent.com/83848415/148326122-a854d256-2556-487e-99be-7d8d58d9b205.png)

### 検証環境：ブラウザ種別

chromeなど

### Web3 インターフェース

MetaMask

### 再現性について

再現できる

### 詳細説明、考察、備考など

discord: https://discord.com/channels/705052448418693180/899916069161041931/926797374154743869

**Comment by taka0409** [comment]
値を入力して確認しましたが表題の現象は確認できませんでした。
ソースも入力値（デフォルトも全体の値）のみを利用して計算しているように見えます。

```
  const fixedTcr = useMemo(() => {
    return props.hasOwnProperty('totalCollateral') ||
      props.hasOwnProperty('totalDebt') ||
      props.hasOwnProperty('rateOfEthJpy')
      ? (100 * totalCollateral * rateOfEthJpy) / totalDebt
      : tcr;
  }, [props, totalDebt, totalCollateral, rateOfEthJpy, tcr]);
```

不具合であるとしたら、フォームの入力値、それによって計算されるTCR、正しいTCRのサンプルを頂きたいです。

**Comment by taka0409** [comment]
かしこまりました。
