### ISSUE TITLE
担保率と手数料が誤った計算値となっている

### ISSUE THREAD

**Issue by fortunecrypto** [DeFiGeek-Community/yamato-interface#97]
### 現象の種類

A 動作の問題

### 見つかった現象及び動作

・多数の箇所に影響
1. UI上で担保率165％を下回る数値（110-165%）での借入が失敗する
2. コントラクト直実行でも同様に失敗する
3. 借入時にかかる手数料が理論値と異なっている
担保率と実際にかかった手数料の実測値
---------------
担保率750%： 0.1％
担保率714%： 0.18％
担保率666%： 0.27%
担保率600%：0.4%
担保率500%： 0.613%
担保率400%： 0.75%
担保率375% :  0.85％
担保率333％： 0.94％
担保率300％： 1％
担保率250％： 1.67%
担保率200％： 3.67%
担保率187.5％： 8%
担保率166.67%： 19.12％ 
担保率165％未満は借り入れ不可（エラー）

### 問題のTxn Hash

https://rinkeby.etherscan.io/tx/0x4f14c41f33c2ef25ad56dd8da2857e84d17e820a04d453b5b8b7aa5ef44f9be4

恐らく165-750％の間の全ての借入トランザクションが該当しているものと推測

### 検証環境：ブラウザ種別

Chrome

### Web3 インターフェース

MetaMask、Etherscan（コントラクト直）

### 再現性について

再現できる

### 再現手順

1. 借入後の担保率を165%～750%未満に設定して借り入れを実施
2. 借入たCJPYとFeeで引かれたCJPYを計算
3. 110％～165％未満の担保率の場合はUI上、コントラクト上のどちらの場合もエラーが発生

### 詳細説明、考察、備考など

コードを見たものの原因不明…
FR関数か、mintCJPY関数あたりのパラメータが意図しない数値として計算されている可能性

実測値から逆算すると、110% → 165％に、500%→ 750％ に設定値が変わってしまっているため、1.5倍の数値となっている。
110x1.5 = 165
500x1.5 = 750
ソースのどこかに1.5を掛ける係数が影響している？

**Comment by 0xTeaTwo** [comment]
仕様バグ。コントラクト側の対応。

**Comment by 0xTeaTwo** [comment]
コントラクト側で変更完了
