### ISSUE TITLE
手数料が事前に分かるようにしたい

### ISSUE THREAD

**Issue by fortunecrypto** [DeFiGeek-Community/yamato-interface#98]
### 要望の種類

B UIについて

### 新機能や改善の概要

現状では借入時の手数料が実行してみるまで分からないので、今表示されている「変動予測値表示...xxxxxCJPY, 担保率xxxxx%」に加えて予測表示に実行後に受け取る予定のCJPY数を表示して欲しい

**Comment by 0xTeaTwo** [comment]
どう表示するか？すでに横幅に余裕ないため2行目にするか？

figmaが欲しい

#97 とブロック

**Comment by 0xTeaTwo** [comment]
closed with #126
